name: ci-main-pipeline
on: 
  push:
    branches:
      - main
      - develop
  pull_request: 
    branches:
      - main
      - develop
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [16, 18, 20]
        include:
          - os: windows-latest
            node_version: 22
        exclude:
          - os: ubuntu-latest
            node_version: 16
          - os: windows-latest
            node_version: 18
          - os: macos-latest
            node_version: 20
      max-parallel: 2

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-node-${{ matrix.node }}
          path: ./build

  conditional-job:
    if: github.ref == 'refs/heads/main'  # Ce job ne s'exécute que sur la branche main
    runs-on: ubuntu-latest
    needs: build  # Exige que le job 'build' soit terminé

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-ubuntu-latest-node-18  # Spécifique à Ubuntu + Node 18

      - name: Simulate deployment
        run: echo "Deploying the application built with Ubuntu and Node 18..."